# library_data.py
# Static metadata for all books in the Digital Library.
# PDFs are hosted on Google Drive — pdf_url should be the Drive "preview" link,
# e.g. https://drive.google.com/file/d/FILE_ID/preview
# (the BookReader frontend swaps /preview -> /view when it needs to jump to a page)

BOOKS = {
    "ncert-eco-macro-12": {
        "id": "ncert-eco-macro-12",
        "title": "Introductory Macroeconomics",
        "author": "NCERT",
        "class_level": "12",
        "subject": "Economics",
        "cover": "https://covers.example.com/macro-12.jpg",
        "pdf_url": "https://drive.google.com/file/d/REPLACE_WITH_FILE_ID/preview",
        "total_pages": 180,
        "difficulty": "Medium",
        "chapters": [
            {"title": "Introduction", "page": 1},
            {"title": "National Income and Related Aggregates", "page": 10},
            {"title": "Money and Banking", "page": 45},
            {"title": "Determination of Income and Employment", "page": 78},
            {"title": "Government Budget and the Economy", "page": 120},
            {"title": "Balance of Payments", "page": 150},
        ],
    },
    "ncert-eco-macro-12-part2": {
        "id": "ncert-eco-macro-12-part2",
        "title": "Indian Economic Development",
        "author": "NCERT",
        "class_level": "12",
        "subject": "Economics",
        "cover": "https://covers.example.com/indian-eco-12.jpg",
        "pdf_url": "https://drive.google.com/file/d/REPLACE_WITH_FILE_ID/preview",
        "total_pages": 210,
        "difficulty": "Medium",
        "chapters": [
            {"title": "Indian Economy on the Eve of Independence", "page": 1},
            {"title": "Indian Economy 1950-1990", "page": 30},
            {"title": "Liberalisation, Privatisation and Globalisation", "page": 70},
            {"title": "Poverty", "page": 110},
            {"title": "Human Capital Formation in India", "page": 140},
            {"title": "Rural Development", "page": 175},
        ],
    },
    "ncert-history-themes-1": {
        "id": "ncert-history-themes-1",
        "title": "Themes in Indian History - Part I",
        "author": "NCERT",
        "class_level": "12",
        "subject": "History",
        "cover": "https://covers.example.com/history-part2.jpg",
        "pdf_url": "https://drive.google.com/file/d/1yzC_cHsbd8zIk30QxEj-xR80i4QrWzt_/preview",
        "total_pages": 117,
        "difficulty": "Hard",
        "chapters": [
            {"title": "Bricks, Beads And Bones", "page": 1},
            {"title": "Kings, Farmers And Towns", "page": 31},
            {"title": "Kinship, Caste And Class", "page": 56},
            {"title": "Thinkers, Beliefs And Buildings", "page": 85},
        ],
    },
    "ncert-history-themes-2": {
        "id": "ncert-history-themes-2",
        "title": "Themes in Indian History - Part II",
        "author": "NCERT",
        "class_level": "12",
        "subject": "History",
        "cover": "https://covers.example.com/history-part2.jpg",
        "pdf_url": "https://drive.google.com/file/d/1XLKPmP8O22uoQJ5A1xdOKbnJeIay2hEG/preview",
        "total_pages": 117,
        "difficulty": "Hard",
        "chapters": [
            {"title": "Through The Eyes Of Travelers", "page": 4},
            {"title": "Bhakti-Sufi Tradition", "page": 29},
            {"title": "An Imperial Capital: Vijayanagara", "page": 59},
            {"title": "Peasents, Zamindars And The State", "page": 85},
        ],
    },
    "ncert-history-themes-3": {
        "id": "ncert-history-themes-3",
        "title": "Themes in Indian History - Part III",
        "author": "NCERT",
        "class_level": "12",
        "subject": "History",
        "cover": "https://covers.example.com/history-part2.jpg",
        "pdf_url": "https://drive.google.com/file/d/1Q7m8Mt_8Zw_Cr-KFKu1kvAelzpYXq0yA/preview",
        "total_pages": 117,
        "difficulty": "Hard",
        "chapters": [
            {"title": "A", "page": 1},
            {"title": "Kings, Farmers And Towns", "page": 31},
            {"title": "Kinship, Caste And Class", "page": 56},
            {"title": "Thinkers, Beliefs And Buildings", "page": 85},
        ],
    },
    "ncert-indian-Politics": {
        "id": "Indian-Polity",
        "title": "Politics In India Since Independence",
        "author": "NCERT",
        "class_level": "12",
        "subject": "Political Science",
        "cover": "https://covers.example.com/history-part2.jpg",
        "pdf_url": "https://drive.google.com/file/d/1Q7m8Mt_8Zw_Cr-KFKu1kvAelzpYXq0yA/preview",
        "total_pages": 117,
        "difficulty": "Hard",
        "chapters": [
            {"title": "A", "page": 1},
            {"title": "Kings, Farmers And Towns", "page": 31},
            {"title": "Kinship, Caste And Class", "page": 56},
            {"title": "Thinkers, Beliefs And Buildings", "page": 85},
        ],
    },
    "ncert-physics-part1-12": {
        "id": "ncert-physics-part1-12",
        "title": "Physics Part I",
        "author": "NCERT",
        "class_level": "12",
        "subject": "Physics",
        "cover": "https://covers.example.com/physics-part1.jpg",
        "pdf_url": "https://drive.google.com/file/d/REPLACE_WITH_FILE_ID/preview",
        "total_pages": 320,
        "difficulty": "Hard",
        "chapters": [
            {"title": "Electric Charges and Fields", "page": 1},
            {"title": "Electrostatic Potential and Capacitance", "page": 50},
            {"title": "Current Electricity", "page": 110},
            {"title": "Moving Charges and Magnetism", "page": 160},
        ],
    },
    "ncert-political-science-2": {
        "id": "ncert-political-science-2",
        "title": "Politics in India Since Independence",
        "author": "NCERT",
        "class_level": "12",
        "subject": "Political Science",
        "cover": "https://covers.example.com/polsci-part2.jpg",
        "pdf_url": "https://drive.google.com/file/d/REPLACE_WITH_FILE_ID/preview",
        "total_pages": 150,
        "difficulty": "Medium",
        "chapters": [
            {"title": "Era of One-Party Dominance", "page": 1},
            {"title": "Politics of Planned Development", "page": 40},
            {"title": "India's External Relations", "page": 90},
        ],
    },
    "vistas-12-ch1": {
        "id": "vistas-12-ch1",
        "title": "The Third Level",
        "book_title": "Vistas",
        "author": "NCERT",
        "class_level": "12",
        "subject": "English",
        "cover": "https://covers.example.com/vistas-12.jpg",
        "pdf_url": "https://drive.google.com/file/d/12KafWzgPschCfZd8uQXoitj62mvrFmWG/preview",
    },
    "vistas-12-ch2": {
        "id": "vistas-12-ch2",
        "title": "The Tiger King",
        "book_title": "Vistas",
        "author": "NCERT",
        "class_level": "12",
        "subject": "English",
        "cover": "https://covers.example.com/vistas-12.jpg",
        "pdf_url": "https://drive.google.com/file/d/10FZvTmm_2-UUeLQkOEAB0VLm5VfkZiL2/preview",
    },
    "vistas-12-ch3": {
        "id": "vistas-12-ch3",
        "title": "Journey to the End of the Earth",
        "book_title": "Vistas",
        "author": "NCERT",
        "class_level": "12",
        "subject": "English",
        "cover": "https://covers.example.com/vistas-12.jpg",
        "pdf_url": "https://drive.google.com/file/d/1oVZ-A2oFVxSN8HdQd1QQUdPe2c-ZWOkh/preview",
    },
    "vistas-12-ch4": {
        "id": "vistas-12-ch4",
        "title": "The Enemy",
        "book_title": "Vistas",
        "author": "NCERT",
        "class_level": "12",
        "subject": "English",
        "cover": "https://covers.example.com/vistas-12.jpg",
        "pdf_url": "https://drive.google.com/file/d/1Uya1WUKK_CIzdqXhF87mi6IJtSlHYjCd/preview",
    },
    "vistas-12-ch5": {
        "id": "vistas-12-ch5",
        "title": "Should Wizard Hit Mommy",
        "book_title": "Vistas",
        "author": "NCERT",
        "class_level": "12",
        "subject": "English",
        "cover": "https://covers.example.com/vistas-12.jpg",
        "pdf_url": "https://drive.google.com/file/d/1SySZjz_MkL4H-uKRv5vTHmCvfwkYDTXC/view?usp=sharing/preview",
    },
    "vistas-12-ch6": {
        "id": "vistas-12-ch6",
        "title": "On the Face of It",
        "book_title": "Vistas",
        "author": "NCERT",
        "class_level": "12",
        "subject": "English",
        "cover": "https://covers.example.com/vistas-12.jpg",
        "pdf_url": "https://drive.google.com/file/d/REPLACE_WITH_FILE_ID_CH6/preview",
    },
    "vistas-12-ch7": {
        "id": "vistas-12-ch7",
        "title": "Evans Tries an O-Level",
        "book_title": "Vistas",
        "author": "NCERT",
        "class_level": "12",
        "subject": "English",
        "cover": "https://covers.example.com/vistas-12.jpg",
        "pdf_url": "https://drive.google.com/file/d/REPLACE_WITH_FILE_ID_CH7/preview",
    },
    "vistas-12-ch8": {
        "id": "vistas-12-ch8",
        "title": "Memories of Childhood",
        "book_title": "Vistas",
        "author": "NCERT",
        "class_level": "12",
        "subject": "English",
        "cover": "https://covers.example.com/vistas-12.jpg",
        "pdf_url": "https://drive.google.com/file/d/REPLACE_WITH_FILE_ID_CH8/preview",
    },
    "Flamingo-12-ch1": {
        "id": "Flamingo-12-ch1",
        "title": "The Last Lesson",
        "book_title": "Flamingo",
        "author": "NCERT",
        "class_level": "12",
        "subject": "English",
        "cover": "https://covers.example.com/vistas-12.jpg",
        "pdf_url": "https://drive.google.com/file/d/12KafWzgPschCfZd8uQXoitj62mvrFmWG/preview",
    },
    "Flamingo-12-ch2": {
        "id": "Flamingo-12-ch2",
        "title": "Lost Spring",
        "book_title": "Flamingo",
        "author": "NCERT",
        "class_level": "12",
        "subject": "English",
        "cover": "https://covers.example.com/vistas-12.jpg",
        "pdf_url": "https://drive.google.com/file/d/1RXXU-BPhRX_ntowEDyjRPOIporhz4Voa/view?usp=sharing/preview",
    },
    "Flamingo-12-ch3": {
        "id": "Flamingo-12-ch3",
        "title": "Deep Water",
        "book_title": "Flamingo",
        "author": "NCERT",
        "class_level": "12",
        "subject": "English",
        "cover": "https://covers.example.com/vistas-12.jpg",
        "pdf_url": "https://drive.google.com/file/d/1E1I3_6u2QEOIGVZxXUFnPFnF-36QmP78/preview",
    },
    "Flamingo-12-ch4": {
        "id": "Flamingo-12-ch4",
        "title": "The Rattrap",
        "book_title": "Flamingo",
        "author": "NCERT",
        "class_level": "12",
        "subject": "English",
        "cover": "https://covers.example.com/vistas-12.jpg",
        "pdf_url": "https://drive.google.com/file/d/1PG0o0T-oLHTY5w8yFcyfGcbSnu9_cY33/preview",
    },
    "Flamingo-12-ch5": {
        "id": "Flamingo-12-ch5",
        "title": "Indigo",
        "book_title": "Flamingo",
        "author": "NCERT",
        "class_level": "12",
        "subject": "English",
        "cover": "https://covers.example.com/vistas-12.jpg",
        "pdf_url": "https://drive.google.com/file/d/1SySZjz_MkL4H-uKRv5vTHmCvfwkYDTXC/preview",
    },
    "Poem-12-ch1": {
        "id": "Poem-12-ch6",
        "title": "My Mother at 66",
        "book_title": "Flamingo",
        "author": "NCERT",
        "class_level": "12",
        "subject": "English",
        "cover": "https://covers.example.com/vistas-12.jpg",
        "pdf_url": "https://drive.google.com/file/d/1vZzOAZxyIa5b4BxYCeZ5G93grrR28IDN/preview",
    },
}
