# library_data.py
# Static metadata for all books in the Digital Library.
# PDFs are hosted on Google Drive — pdf_url should be the Drive "preview" link,
# e.g. https://drive.google.com/file/d/FILE_ID/preview
# (the BookReader frontend swaps /preview -> /view when it needs to jump to a page)

BOOKS = {
    "ncert-eco-macro-12": {
        "id": "ncert-eco-macro-12",
        "title": "Introductory Macroeconomics",
        "author": "NCERT",
        "class_level": "12",
        "subject": "Economics",
        "cover": "https://covers.example.com/macro-12.jpg",
        "pdf_url": "https://drive.google.com/file/d/REPLACE_WITH_FILE_ID/preview",
        "total_pages": 180,
        "difficulty": "Medium",
        "chapters": [
            {"title": "Introduction", "page": 1},
            {"title": "National Income and Related Aggregates", "page": 10},
            {"title": "Money and Banking", "page": 45},
            {"title": "Determination of Income and Employment", "page": 78},
            {"title": "Government Budget and the Economy", "page": 120},
            {"title": "Balance of Payments", "page": 150},
        ],
    },
    "ncert-eco-macro-12-part2": {
        "id": "ncert-eco-macro-12-part2",
        "title": "Indian Economic Development",
        "author": "NCERT",
        "class_level": "12",
        "subject": "Economics",
        "cover": "https://covers.example.com/indian-eco-12.jpg",
        "pdf_url": "https://drive.google.com/file/d/REPLACE_WITH_FILE_ID/preview",
        "total_pages": 210,
        "difficulty": "Medium",
        "chapters": [
            {"title": "Indian Economy on the Eve of Independence", "page": 1},
            {"title": "Indian Economy 1950-1990", "page": 30},
            {"title": "Liberalisation, Privatisation and Globalisation", "page": 70},
            {"title": "Poverty", "page": 110},
            {"title": "Human Capital Formation in India", "page": 140},
            {"title": "Rural Development", "page": 175},
        ],
    },
    "ncert-history-themes-2": {
        "id": "ncert-history-themes-2",
        "title": "Themes in Indian History - Part II",
        "author": "NCERT",
        "class_level": "12",
        "subject": "History",
        "cover": "https://covers.example.com/history-part2.jpg",
        "pdf_url": "https://drive.google.com/file/d/REPLACE_WITH_FILE_ID/preview",
        "total_pages": 240,
        "difficulty": "Hard",
        "chapters": [
            {"title": "Kings, Farmers and Towns", "page": 1},
            {"title": "Kinship, Caste and Class", "page": 45},
            {"title": "Thinkers, Beliefs and Buildings", "page": 95},
        ],
    },
    "ncert-physics-part1-12": {
        "id": "ncert-physics-part1-12",
        "title": "Physics Part I",
        "author": "NCERT",
        "class_level": "12",
        "subject": "Physics",
        "cover": "https://covers.example.com/physics-part1.jpg",
        "pdf_url": "https://drive.google.com/file/d/REPLACE_WITH_FILE_ID/preview",
        "total_pages": 320,
        "difficulty": "Hard",
        "chapters": [
            {"title": "Electric Charges and Fields", "page": 1},
            {"title": "Electrostatic Potential and Capacitance", "page": 50},
            {"title": "Current Electricity", "page": 110},
            {"title": "Moving Charges and Magnetism", "page": 160},
        ],
    },
    "ncert-political-science-2": {
        "id": "ncert-political-science-2",
        "title": "Politics in India Since Independence",
        "author": "NCERT",
        "class_level": "12",
        "subject": "Political Science",
        "cover": "https://covers.example.com/polsci-part2.jpg",
        "pdf_url": "https://drive.google.com/file/d/REPLACE_WITH_FILE_ID/preview",
        "total_pages": 150,
        "difficulty": "Medium",
        "chapters": [
            {"title": "Era of One-Party Dominance", "page": 1},
            {"title": "Politics of Planned Development", "page": 40},
            {"title": "India's External Relations", "page": 90},
        ],
    },
}
